# Default values for pm4ml-experience-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: modusbox-mbx-docker.jfrog.io/modusintegration/mojaloop-payment-manager-experience-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullCredentials:
  user: mbx-cicd-deployer
  pass: KWtgDzg4Z@7i/h,x8jgy
  registry: modusbox-mbx-docker.jfrog.io

nameOverride: ""
fullnameOverride: ""  

service:
  type: NodePort
  port: 8084

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#### ENV values
env:
  enableMockData: false
